/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Negocio.*;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author juan2ramos
 */
public class Libros extends javax.swing.JInternalFrame {

    /**
     * Creates new form Libros
     */
    public Libros() {
        initComponents();
        llenarLibros();
        llenarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tituloTxt = new javax.swing.JTextField();
        isbnTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listLibros = new javax.swing.JList();
        ejemplaresTxt = new javax.swing.JTextField();
        prestamosTxt = new javax.swing.JTextField();
        autorTxt = new javax.swing.JComboBox();
        materiaTxt = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");

        jLabel1.setText("Libros");

        jLabel2.setText("ISBN");

        jLabel3.setText("Autor");

        jLabel4.setText("Materia");

        jLabel5.setText("#Ejemplares ");

        jLabel6.setText("#prestamos");

        jLabel7.setText("Titulo");

        listLibros.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listLibrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listLibros);

        ejemplaresTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemplaresTxtActionPerformed(evt);
            }
        });

        autorTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        materiaTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tituloTxt)
                            .addComponent(isbnTxt)
                            .addComponent(ejemplaresTxt)
                            .addComponent(prestamosTxt)
                            .addComponent(autorTxt, 0, 209, Short.MAX_VALUE)
                            .addComponent(materiaTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tituloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(isbnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(autorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(materiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ejemplaresTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(prestamosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void llenarLibros() {
        ArrayList<Libro> Libros = LibroController.getInstance().getLibroArray();
        listLibros.setListData(Libros.toArray());
    }

    public void llenarDatos() {
        ArrayList<Negocio.Materia> materias = LibroController.getInstance().materias();
        DefaultComboBoxModel comboModel = new javax.swing.DefaultComboBoxModel(materias.toArray());
        materiaTxt.setModel(comboModel);

        ArrayList<Negocio.Autor> autores = (ArrayList) LibroController.getInstance().autores();
        DefaultComboBoxModel comboModel1 = new javax.swing.DefaultComboBoxModel(autores.toArray());
        autorTxt.setModel(comboModel1);
    }
    private void ejemplaresTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemplaresTxtActionPerformed
        
        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_ejemplaresTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HashMap hashMap = new HashMap();
        hashMap.put("titulo", tituloTxt.getText());
        hashMap.put("isbn", isbnTxt.getText());
        hashMap.put("autor", autorTxt.getSelectedItem());
        hashMap.put("materia", materiaTxt.getSelectedItem());
        hashMap.put("numero_ejemplares", Integer.parseInt(ejemplaresTxt.getText()));
        hashMap.put("numero_prestamos", Integer.parseInt(prestamosTxt.getText()));
        LibroController.getInstance().llenarLibro(hashMap);
        llenarLibros();   // TODO add your handling code here:


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HashMap hashMap = new HashMap();
        Negocio.Libro libro = (Negocio.Libro) listLibros.getSelectedValue();
        hashMap.put("codigo", libro.getId());
        hashMap.put("titulo", tituloTxt.getText());
        hashMap.put("isbn", isbnTxt.getText());
        hashMap.put("autor", autorTxt.getSelectedItem());
        hashMap.put("materia", materiaTxt.getSelectedItem());
        hashMap.put("numero_ejemplares", Integer.parseInt(ejemplaresTxt.getText()));
        hashMap.put("numero_prestamos", Integer.parseInt(prestamosTxt.getText()));
        LibroController.getInstance().actualizarLibro(libro, hashMap);
        llenarLibros();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void listLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listLibrosMouseClicked
        // TODO add your handling code here:
        Libro libro = (Libro) listLibros.getSelectedValue();
        tituloTxt.setText(libro.getTitiulo());
        isbnTxt.setText(libro.getIsbn());
        autorTxt.setSelectedItem(libro.getAutor());
        materiaTxt.setSelectedItem(libro.getMateria());
        ejemplaresTxt.setText(Integer.toString(libro.getNumeroEjemplares()));
        prestamosTxt.setText(Integer.toString(libro.getNumeroPrestamos()));
    }//GEN-LAST:event_listLibrosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox autorTxt;
    private javax.swing.JTextField ejemplaresTxt;
    private javax.swing.JTextField isbnTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listLibros;
    private javax.swing.JComboBox materiaTxt;
    private javax.swing.JTextField prestamosTxt;
    private javax.swing.JTextField tituloTxt;
    // End of variables declaration//GEN-END:variables
}
