/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Negocio.*;
import Negocio.TipoCliente;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author juan2ramos
 */
public class Prestamo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reservas
     */
    public Prestamo() {
        initComponents();
        llenarDatos();
        llenarPrestamo();
    }

    public void llenarPrestamo() {
        ArrayList<Negocio.Prestamo> prestamos = PrestamoController.getInstance().getPrestamoArray();
        listaPrestamo.setListData(prestamos.toArray());
    }

    public void llenarDatos() {
        ArrayList<Negocio.Cliente> clientes = PrestamoController.getInstance().cliente();
        DefaultComboBoxModel comboModel = new javax.swing.DefaultComboBoxModel(clientes.toArray());
        clienteTxt.setModel(comboModel);

        ArrayList<Negocio.Libro> libros = (ArrayList) PrestamoController.getInstance().libro();
        DefaultComboBoxModel comboModel1 = new javax.swing.DefaultComboBoxModel(libros.toArray());
        libroTxt.setModel(comboModel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fechaTxt = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        clienteTxt = new javax.swing.JComboBox();
        libroTxt = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPrestamo = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        devolucionTxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        fechaTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        fechaTxt.setToolTipText("12/12/1985");

        jButton1.setText("Generara prestamo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        jLabel2.setText("Libro");

        jLabel3.setText("Fecha de prestamo");

        jLabel4.setText("Prestamos");

        clienteTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        libroTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        listaPrestamo.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPrestamoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaPrestamo);

        jLabel5.setText("Fecha devolucion");

        jButton3.setText("Actualizar Prestamo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(340, 340, 340))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaTxt)
                            .addComponent(clienteTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(libroTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(devolucionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(libroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(devolucionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(PrestamoController.getInstance().validarExistencias((Libro) libroTxt.getSelectedItem())){
       
            HashMap hashMap = new HashMap();
            hashMap.put("fecha", fechaTxt.getText());
            hashMap.put("fecha_devolucion", devolucionTxt.getText());
            hashMap.put("codigo", PrestamoController.id + 1);
            hashMap.put("codigo_cliente", (Cliente) clienteTxt.getSelectedItem());
            hashMap.put("codigo_libro", (Libro) libroTxt.getSelectedItem());
            PrestamoController.getInstance().llenarPrestamo(hashMap);
            llenarPrestamo();
        }else{
            JOptionPane.showInternalMessageDialog(rootPane, "No hay mas existencias");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Negocio.Prestamo prestamo = (Negocio.Prestamo) listaPrestamo.getSelectedValue();

        HashMap hashMap = new HashMap();

        hashMap.put("codigo", prestamo.getId());
        hashMap.put("fecha", fechaTxt.getText());
        hashMap.put("fecha_devolucion", devolucionTxt.getText());

        hashMap.put("codigo_cliente", (Cliente) clienteTxt.getSelectedItem());
        hashMap.put("codigo_libro", (Libro) libroTxt.getSelectedItem()); // TODO add your handling code here:
        PrestamoController.getInstance().actualizarPrestamos(prestamo, hashMap);
        llenarPrestamo();


    }//GEN-LAST:event_jButton3ActionPerformed

    private void listaPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPrestamoMouseClicked
        Negocio.Prestamo prestamo = (Negocio.Prestamo) listaPrestamo.getSelectedValue();
        fechaTxt.setText(prestamo.getFecha());
        devolucionTxt.setText(prestamo.getFechaDevolucion());
        clienteTxt.setSelectedItem(prestamo.getCliente());
        libroTxt.setSelectedItem(prestamo.getLibro());

// TODO add your handling code here:
    }//GEN-LAST:event_listaPrestamoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox clienteTxt;
    private javax.swing.JTextField devolucionTxt;
    private javax.swing.JFormattedTextField fechaTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox libroTxt;
    private javax.swing.JList listaPrestamo;
    // End of variables declaration//GEN-END:variables
}
